name: elks
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - xeus-cling
  - earthpy
  - hydrofunctions
  - seaborn
  - scikit-learn
  - sympy
  - pytorch
  - torchvision
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - recommonmark

